server:
  port: 8001
mybatis:
  type-aliases-package: com.itlike.pojo  # 所有Entity别名类所在包
  mapper-locations: classpath:mapper/*.xml       # mapper映射文件
  configuration:
    map-underscore-to-camel-case: true
spring:
  dubbo:
    application:
      name: student_provider
      registry:
        address: zookeeper://192.168.2.128
        port: 2181
      protocol:
        name: dubbo
        port: 20880
      scan:
        base-packages: com.tjetc.service #扫描的包名
  application:
    name: student_provider #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springboot_dubbo?serverTimezone=GMT%2B8  # 数据库名称
    username: root
    password: 206976
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间
logging:
  level:
    com.itlike.mapper: debug